#!/bin/sh
set -eu

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<SQL
CREATE EXTENSION IF NOT EXISTS citext;
CREATE ROLE spendpilot_migrator LOGIN PASSWORD '${SPENDPILOT_MIGRATOR_PASSWORD}'
    NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE;
CREATE ROLE spendpilot_app LOGIN PASSWORD '${SPENDPILOT_APP_PASSWORD}'
    NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE;
GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO spendpilot_migrator, spendpilot_app;
ALTER SCHEMA public OWNER TO spendpilot_migrator;
GRANT USAGE ON SCHEMA public TO spendpilot_app;
SQL
